site_name: PracticalKungFu.net
site_url: https://practicalkungfu.net/
theme:
  name: material
  palette:
    scheme: slate
  features:
    - content.code.copy
    - content.code.select
    - navigation.instant

plugins:
  - blog:
      blog_toc: true
      archive_toc: true
      categories_toc: true
      post_readtime: false
      draft: false
      draft_if_future_date: true
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Blog: blog/index.md
  - About: about.md