site_name: PracticalKungFu.net
site_url: https://www.practicalkungfu.net/
repo_url: https://github.com/PracticalKungFu/practicalkungfu.github.io
repo_name: practicalkungfu.github.io
theme:
  name: material
  palette:
    scheme: slate
  features:
    - content.code.copy
    - content.code.select
    - navigation.instant
    - navigation.tracking
    - navigation.path
    - navigation.top

plugins:
  - blog:
      blog_dir: ./
      blog_toc: true
      archive_toc: true
      categories_toc: true
      post_readtime: false
      draft: false
      draft_on_serve: true
      draft_if_future_date: true
  - search
  - rss:
      match_path: posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Articles: index.md
  - About: about.md